export const RolesEnum = {
  ADMINISTRADOR: 'ADMINISTRADOR',
  DIRETOR: 'DIRETOR',
  OUTROS: 'OUTROS'
}

export const TypeUserEnum = {
  ADMINISTRADOR: 'ADMINISTRADOR',
  MANAGMENT_CONSULTANT_VISIT: 'MANAGMENT_CONSULTANT_VISIT',
  INSPECTOR_QUALITY: 'INSPECTOR_QUALITY',
  MANAGMENT_INSPECTOR_QUALITY: 'MANAGMENT_INSPECTOR_QUALITY',
  OTHERS: 'OTHERS'
}

export const ScopesEnum = {
  USERS_READ: 'USERS_READ',
  USERS_CREATE: 'USERS_CREATE',
  USERS_EDIT: 'USERS_EDIT',
  USERS_INACTIVE: 'USERS_INACTIVE',
  USERS_REACTIVE: 'USERS_REACTIVE',
  SCHEDULE_READ: 'SCHEDULE_READ',
  SCHEDULE_CREATE: 'SCHEDULE_CREATE',
  SCHEDULE_EDIT: 'SCHEDULE_EDIT',
  SCHEDULE_DELETE: 'SCHEDULE_DELETE',
  ROUTES_READ: 'ROUTES_READ',
  VISIT_ROUTES_READ: 'VISIT_ROUTES_READ',
  VISIT_VISIT_READ: 'VISIT_VISIT_READ',
}
