export enum routesType {
  AUTH_ROOT = "/auth/login",
  AUTH_REGISTER = "/auth/register",
  ROOT = "/",
  HOME = "/home",
  USER = "/user",
  USER_LIST = "/user/",
  USER_PROFILE = "/user/profile/:id",
  USER_EDIT = "/user/edit",
  SCHEDULE_LIST = "/schedule/",
  USER_SCHEDULE = "/schedule/user",
  SCHEDULE_EDIT = "/schedule/edit/:id",
  LAUNDRY_LIST = "/laundry",
  BOLSISTA_AREA = "/bolsista-area",
}
